version: "3"
services:
  db-master:
    container_name: master
    build:
      context: ./masterdb
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    # Where our data will be persisted
    volumes:
      - ./share:/share/
      - my-db-master:/var/lib/mysql
      - my-db-master:/var/lib/mysql-files
    networks:
      - net-mysql

  db-slave:
    container_name: slave1
    build:
      context: ./slavedb
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_REPL_USER: 'repl'
      MYSQL_REPL_PASSWORD: '1234'
    ports:
      - '3307:3306'
    # Where our data will be persisted
    volumes:
      - my-db-slave:/var/lib/mysql
      - my-db-slave:/var/lib/mysql-files
    networks:
      - net-mysql

# Names our volume
volumes:
  my-db-master:
  my-db-slave:


networks:
  net-mysql:
    driver: bridge
